# -*- coding: utf-8 -*-
"""CRISP-DM analysis COVID.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vymqxHAHwaYh2ZlNmhd5TNGkLl6Zgumm
"""

import pandas as pd

data = pd.read_csv('covid.csv')

data.head()

data.describe()

